-- Clean slate for re-runs (optional)
DELETE FROM P1_SWIFT_OUTBOX;
DELETE FROM P1_AUDIT_LOG;
DELETE FROM P1_PAYMENTS;

-- A) Clean (should pass all stages)
INSERT INTO P1_PAYMENTS (FROM_ACCT, TO_BENENAME, TO_BENEBIC, AMT, CURR)
VALUES ('ACCT0000000001','GLOBAL TRADERS LLC','BOFAUS3NXXX', 1250.50, 'USD');

-- B) OFAC hit (blocked due to keyword)
INSERT INTO P1_PAYMENTS (FROM_ACCT, TO_BENENAME, TO_BENEBIC, AMT, CURR)
VALUES ('ACCT0000000002','ACME TERROR EXPORTS','CHASUS33XXX', 300.00, 'USD');

-- C) Another clean
INSERT INTO P1_PAYMENTS (FROM_ACCT, TO_BENENAME, TO_BENEBIC, AMT, CURR)
VALUES ('ACCT0000000003','SRI ANNAPOORNA MESS','HDFCINBBXXX', 75.25, 'USD');
