 CREATE OR REPLACE PROCEDURE P1_EOD_BATCH ()
LANGUAGE SQL
BEGIN
  DECLARE v_pay INT DEFAULT 0;

  DECLARE c1 CURSOR FOR
    SELECT PAY_ID FROM P1_PAYMENTS WHERE STATUS='NEW' ORDER BY PAY_ID;

  FOR c1_row AS c1 CURSOR FOR
    SELECT PAY_ID FROM P1_PAYMENTS WHERE STATUS='NEW' ORDER BY PAY_ID
  DO
    CALL P1_SCREEN_PAYMENT(c1_row.PAY_ID);

    IF (SELECT STATUS FROM P1_PAYMENTS WHERE PAY_ID=c1_row.PAY_ID) = 'APPROVED' THEN
      CALL P1_POST_GL(c1_row.PAY_ID);
      CALL P1_QUEUE_SWIFT(c1_row.PAY_ID);
    END IF;
  END FOR;

  INSERT INTO P1_AUDIT_LOG (ENTITY, ACTION, DETAILS)
  VALUES ('BATCH','RUN','P1_EOD_BATCH completed');
END;