CREATE OR REPLACE PROCEDURE P1_SCREEN_PAYMENT (IN p_pay_id INT)
LANGUAGE SQL
BEGIN
  DECLARE v_name VARCHAR(60);
  DECLARE v_hits INT DEFAULT 0;

  SELECT TO_BENENAME INTO v_name FROM P1_PAYMENTS WHERE PAY_ID = p_pay_id;

  SELECT COUNT(*) INTO v_hits
  FROM P1_SANCTIONS
  WHERE LIST_TYPE='OFAC'
    AND UPPER(v_name) LIKE '%' || UPPER(NAME_PATTERN) || '%';

  IF v_hits > 0 THEN
    UPDATE P1_PAYMENTS
       SET STATUS='OFAC_HIT',
           REASON='Hit on sanctions list'
     WHERE PAY_ID=p_pay_id;

    INSERT INTO P1_AUDIT_LOG (ENTITY, REF_ID, ACTION, DETAILS)
    VALUES ('SCREEN', CAST(p_pay_id AS VARCHAR(20)), 'BLOCK', 'OFAC hit detected');
  ELSE
    UPDATE P1_PAYMENTS
       SET STATUS='APPROVED',
           REASON=NULL
     WHERE PAY_ID=p_pay_id;

    INSERT INTO P1_AUDIT_LOG (ENTITY, REF_ID, ACTION, DETAILS)
    VALUES ('SCREEN', CAST(p_pay_id AS VARCHAR(20)), 'APPROVE', 'No hits');
  END IF;
END;