-- === MASTER / REFERENCE ===
CREATE TABLE P1_GL_ACCOUNTS (        -- GL master
  GL_ACCT       CHAR(10)     NOT NULL PRIMARY KEY,
  ACCT_NAME     VARCHAR(40)  NOT NULL,
  BALANCE       DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE P1_CUSTOMER_ACCTS (     -- Customer account master (Equation-like)
  CUST_ACCT     CHAR(14)     NOT NULL PRIMARY KEY,
  CUST_NAME     VARCHAR(50)  NOT NULL,
  CURR          CHAR(3)      NOT NULL DEFAULT 'USD',
  BALANCE       DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE P1_SANCTIONS (          -- e-Gifts: screening list (very small mock OFAC)
  LIST_TYPE     VARCHAR(10)  NOT NULL,  -- 'OFAC'
  NAME_PATTERN  VARCHAR(60)  NOT NULL
);

-- === TRANSACTIONAL ===
CREATE TABLE P1_PAYMENTS (           -- Incoming payment requests (pre-screen)
  PAY_ID        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FROM_ACCT     CHAR(14)     NOT NULL,
  TO_BENENAME   VARCHAR(60)  NOT NULL,     -- beneficiary name to screen
  TO_BENEBIC    CHAR(11)     NOT NULL,     -- BIC for SWIFT
  AMT           DECIMAL(15,2) NOT NULL,
  CURR          CHAR(3)      NOT NULL DEFAULT 'USD',
  STATUS        VARCHAR(12)  NOT NULL DEFAULT 'NEW',  -- NEW/OFAC_HIT/APPROVED/POSTED/SENT
  REASON        VARCHAR(80)  DEFAULT NULL,
  CRT_TS        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE P1_SWIFT_OUTBOX (       -- Outbound SWIFT messages queue
  MSG_ID        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PAY_ID        INTEGER      NOT NULL,
  MT_TYPE       CHAR(6)      NOT NULL,     -- e.g., 'MT103'
  RAW_TEXT      CLOB(10K)    NOT NULL,
  STATUS        VARCHAR(12)  NOT NULL DEFAULT 'QUEUED', -- QUEUED/SENT
  CRT_TS        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE P1_AUDIT_LOG (          -- Simple audit/events log
  LOG_ID        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ENTITY        VARCHAR(20)  NOT NULL,     -- 'SCREEN','GL','SWIFT','BATCH'
  REF_ID        VARCHAR(20)  NULL,         -- e.g., PAY_ID or GL ref
  ACTION        VARCHAR(20)  NOT NULL,
  DETAILS       VARCHAR(200) NOT NULL,
  CRT_TS        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
